film_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from films import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home),
    url(r'^films$', views.films),
    url(r'^series$', views.series),
    url(r'^aide$', views.show_help),
    url(r'^news$', views.news),
    url(r'^news/ajouts$', views.news_add),
    url(r'^news/suppressions$', views.news_suppr),
    url(r'^news/autres$', views.news_other),
    url(r'^admin/', include(admin.site.urls)),
)

films/models.py
from django.db import models
from django.conf import settings

class Film(models.Model):
    title = models.CharField('title', max_length=50)
    language = models.CharField('language', max_length=10, blank=True)
    quality = models.CharField('quality', max_length=10, blank=True)
    rating = models.FloatField('rating', default=0, blank=True)
    film = models.BooleanField('film', blank=True)
    image = models.CharField('image', max_length=50, blank=True)
    synopsis = models.TextField('synopsis', blank=True)
    imdb = models.CharField('imdb', max_length=70, blank=True)
    
    def admin_image(self):
        return '<img src="%s"/>' \
               % (settings.STATIC_URL + "images/" + self.title + ".jpg")
    admin_image.allow_tags = True

    def __unicode__(self):
        if self.film:
            return "Film " + self.title
        return "Serie " + self.title

class Links(models.Model):
    film = models.ForeignKey(Film)
    name = models.CharField('name', max_length=50)
    short_name = models.CharField('short_name', max_length=30)
    link = models.CharField('link', max_length=300)

class News(models.Model):
    date = models.DateTimeField('date published')
    message = models.TextField('message')
    CAT_CHOICES = (
        ('Ajout', 'Ajout'),
        ('Suppression', 'Suppression'),
        ('Autre', 'Autre'),
    )
    category = models.CharField('category', max_length=20, choices=CAT_CHOICES)

    def __unicode__(self):
        return self.category + ", " + self.message

films/views.py
from django.shortcuts import render
from django.http import HttpResponse
from films.models import Film, News

def home(request):
    return series(request)

def films(request):
    film_list = Film.objects.order_by('title')
    infos = dict({'film_list': film_list, 'display_film': True})
    return render(request, "films.html", infos)

def series(request):
    film_list = Film.objects.order_by('title')
    infos = dict({'film_list': film_list, 'display_film': False})
    return render(request, "films.html", infos)

def show_help(request):
    return render(request, "help.html")

def news(request):
    news = (News.objects.order_by('date')).reverse()
    infos = dict({'news': news})
    return render(request, "news.html", infos)

def news_add(request):
    news = (News.objects.filter(category="Ajout")).order_by('date').reverse()
    infos = dict({'news': news})
    return render(request, "news.html", infos)

def news_suppr(request):
    news = (News.objects.filter(category="Suppression"))\
            .order_by('date').reverse()
    infos = dict({'news': news})
    return render(request, "news.html", infos)

def news_other(request):
    news = (News.objects.filter(category="Autre")).order_by('date').reverse()
    infos = dict({'news': news})
    return render(request, "news.html", infos)

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html>
    <head>
        <meta charset="utf-8" /> 
        <title>Films et séries</title> 
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
		<link rel="icon" type="image/png" href="./images/favicon.png" />
    </head>
	
	<body>
        {% include "nav.html" %}
        {% include "scripts.html" %}
        
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/films.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}
{% for film in film_list %}
{% if film.film == display_film %}
<div class="film">
    <img src="{% static './images/' %}{{ film.image }}" class="affiche" alt="image_affiche"/>
    
    <div class="synopsis">
        <p>{{ film.synopsis }}</p>
    </div>
    
    <div class="carac">
        <ul>
            <li><a href="{{ film.imdb }}">{{ film.title }}</a></li>
            <li>{{ film.language }}</li>
            <li>{{ film.quality }}</li>
            <li>{{ film.rating }}/10</li>
        </ul>
    </div>
    
    <div class="liens">
        <ul>
        {% for link in film.links_set.all %}
            <li><a href="{{ link.link }}">{{ link.short_name }}</a></li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="trait"></div>
    <div STYLE="clear:both;"></div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

templates/footer.html
<footer>
<hr>
</footer>

templates/help.html
{% extends "base.html" %}

{% block content %}
<div id="aide">
    <h1>Page d'aide</h1>
    <br/>
    <h2>Introduction</h2>
        <p>Beaucoup d'utilisateurs de ce site, donc vous, se sont un jour demandé "Mais qu'est-ce que ça veut dire ce truc là ?!". Longtemps restées sans réponses, les questions de ce genre vont maintenant en avoir une.</p>
        <p>Vous pouvez à tout moment envoyer vos suggestions, demandes à <a href="mailto:contact_film@hatrix.fr">contact_film@hatrix.fr</a>.</p>
        <p>Je tiens également à préciser que ce site n'a qu'un but : l'enrichissement culturel. Tout comme tous les utilisateurs de peer2peer, c'est par le plaisir du partage que je fais cela.</p>
        <p>J'ajoute également que certains éléments comme des séries sous-titrées n'existent pas légalement, ce sont la plupart du temps des amateurs, fans qui les créent.</p>
        <p>Aucun bénéfice, quel qu'il soit n'est généré, qu'il y ait un ou 500 visiteurs. S'il y a un problème, contactez moi.</p>
    <br/>
    
    <h2>Navigation</h2>
        <p>Vous pouvez naviguer sur le site en utilisant les 3 boutons situés en haut de page. Ceux-ci permettent de consulter 3 pages, permettant de télécharger respectivement des films, des séries ou bien de la musique, des jeux.</p>
    <br/>
    
    <h2>Visites</h2>
        <p>Le nombre de visites total et le nombre de visiteurs uniques sont affichés en bas de page séparés par un slash "/".</p>
        <p>Aucun bénéfice n'est toutefois engendré par ce site au profit de qui que ce soit. Aucune pub ne sera également déployée sur ce site.</p>
    <br/>
    
    <h2>Téléchargement</h2>
        <p>Pour télécharger via les liens proposés, il vous suffit soit de cliquer dessus et ensuite d'accéder à ce que vous souhaitez en cliquant encore une fois dessus, soit vous devrez faire un clic droit puis "enregister sous".</p>
        <p>Cette dernière méthode est à utiliser si vous avez installé un logiciel ou un plugin à votre naviguateur pour lire en ligne les contenus multimédia et que vous souhaitez télécharger ces contenus sur votre disque dur.</p>
        <p>Bien entendu, si vous souhaitez visionner en ligne, vous le pouvez via ces logiciels, vous pouvez par exemple utiliser <a href="http://www.videolan.org/vlc/">VLC</a>.</p>
        <p>Notez également que vous ne pouvez pas avancer dans le fichier tant que celui n'a pas téléchargé la partie désirée, le téléchargement commence au début de celui-ci.</p>
    
    <br/>
    <h2>Films et Séries</h2>
        <p>Les films et séries proposés ne sont pas toujours d'une même qualité, il convient donc d'indiquer celle-ci avec les langues disponibles.</p>
        <p>Un synopsys ainsi que ces informations sont renseignées dans plusieurs blocs. Le premier constitue celui du synopsis et le suivant celui des caractéristiques, classées dans cet ordre : langue/qualité/note</p>
        
        <h3>Synopsys</h3>
        <p>Si vous ne connaissez pas ce qui est proposé, vous pouvez lire le synopsys pour vous donner une brève idée de ce dont il est question.</p>
        <p>Vous pouvez obtenir plus d'informations en allant sur Allociné ou IMDB via le lien porposé dans le nom (voir ci-dessous).</p>
        
        <h3>Nom</h3>
        <p>Le premier élément apparaissant dans les cacractéristiques est le nom de la série ou du film. En cliquant dessus, on accède en général à une page Allociné donnant des informations sur ce contenu.</p>
        <p>Il peut cependant arriver qu'Allociné ne dispose pas des informations nécessaires, IMDB est donc choisi. C'est le cas pour Mythbusters par exemple.</p>
        
        <h3>Langue</h3>
        <ul>
            <li>FR : Français (pas québécois)</li>
            <li>Français : Français (pas québécois)</li>
            <li>Anglais : Anglais</li>
            <li>Vo : Langue d'origine</li>
            <li>Vostfr : Langue d'origine, sous-titrée en français</li>
            <li>Multi : Plusieurs langues sont intégrées au fichier. Généralement avec des sous-titres de ces langues.</li>
        </ul>
        
        <h3>Qualité</h3>
        <ul>
            <li>Standard : Qualité satisfaisante, épisodes ˜ 350Mo, films ˜ 700Mo</li>
            <li>Moyenne : Qualité pas vraiment top mais regardable</li>
            <li>720P : HD 720p, bonne qualité</li>
            <li>1080P : HD 1080p, encore mieux</li>
        </ul>
        
        <h3>Note</h3>
        <p>Les notes ne sont en aucun cas attribuées par le webmaster de ce site mais par allociné. Les notes sont telles qu'elles étaient lors de l'ajout du film ou de la série.</p>
        <p>La meilleure note entre celle des spectateurs et de la presse est prise. Elles sont toutes sur 5.</p>
        
        <h3>Liens</h3>
        <p>Les liens apparaissent sous le bloc des cartactéristiques en bleu. Pour les séries, ils équivalent au numéro de la saison. Pour les films, ils équivalent au nom du film, les trilogies étant consignées en un seul "article".</p>
    
    <br/>
    <h2>Foutoir</h2>
        <p>Des albums de musique ainsi que des jeux sont présents sur cette page.</p>
        <p>Il se peut toutefois que des liens vers des jeux ne soient plus fonctionnels.</p>
        
        <h3>Musique</h3>
            <p>L'album, son artiste, ainsi que son genre sont présents dans le tableau. Le lien l'est également sous une autre forme. Celui est placé sur la qualité de l'album en question.</p>
            <p>Pour plus d'informations sur les qualités, visitez ces pages : <a href="http://wiki.hydrogenaudio.org/index.php?title=LAME#VBR_.28variable_bitrate.29_settings">LAME</a>, <a href="http://fr.wikipedia.org/wiki/Variable_bitrate">VBR</a>, <a href="http://fr.wikipedia.org/wiki/Constant_bitrate">CBR</a></p>
            <p>Il peut en effet y en avoir plusieurs différentes, comme avec les films et séries :</p>
           
            <ul>
                <li>Vx : Encodage via LAME, plus le "x" est faible, mieux c'est. V0 : 245VBR</li>
                <li>x VBR : Constant Bitrate, plus c'est haut, mieux c'est.</li>
                <li>x CBR : Variable Bitrate, plus c'est haut, mieux c'est. Plus lourd qu'un VBR.</li>
                <li>FLAC : Losless, qualité irréprochable mais lourd</li>
            </ul>
            
        <h3>Jeux</h3>
            <p>Les notes attribuées sont celles telles qu'elles étaient lorsque le jeu a été ajouté sur le site. Elles sont récupérées à partir de jeuxvideo.com.</p>
            <p>En raison de la place limitée sur le disque dur du serveur, certains jeux peuvent être supprimés en étant tout de même présents sur la page.</p>
</div>

{% include "footer.html" %}
{% endblock %}

templates/nav.html
<nav>
    <ul>
        <li><a href="/films">Films</a></li>
        <li><a href="/series">Séries</a></li>
    </ul>
</nav>

<div id="nav_news">
    <div>
        <a href="/aide">Aide</a>
    </div>
    <div>
        <a href="/news">News</a>
    </div>
</div>

templates/news.html
{% extends "base.html" %}
{% block content %}
<div id="aide_nav">
    <a href="/news">Tout</a>
    <a href="/news/ajouts">Ajouts</a>
    <a href="/news/suppressions">Suppressions</a>
    <a href="/news/autres">Autres</a>
</div>

{% if not news %}
<div class="news">
    <p>Pas de news sous cette catégorie !</p>
</div>
{% else %}
{% for article in news %}
<div class="news">
    <div class="titre_news">
        <h1>{{ article.category }}</h1>
    </div>
    
    <div class="date_news">
        <h2>{{ article.date }}</h2>
    </div>
    <div STYLE="clear:both;"></div>
   
    <p>{{ article.message|linebreaks }}</p>
</div>
<div class="trait"></div>
{% endfor %}
{% endif %}
{% endblock %}


templates/scripts.html
<script type="text/javascript">
    function afficherCacher() {
        if(document.getElementById("liste").style.display == 'block'){
            document.getElementById("liste").style.display = 'none';
        }
        else{
            document.getElementById("liste").style.display = 'block'
        }
    }
    
    function aller(serie){
        window.location.hash = '#' + serie;
        
        if(window.pageYOffset + 1000 > document.body.offsetHeight){
            window.scroll(0,window.pageYOffset);
        }
        else{
            window.scroll(0,window.pageYOffset-window.innerHeight/2+280/2);
        }
    }
</script>